### ISSUE TITLE
How to load and export mesh

### ISSUE THREAD

**Issue by HollowHeartNet** [pyvista/pyacvd#14]
Hi,

I would like to know how to use this library for loading an input mesh from my hard disk and then exporting the remeshed output, for example in OBJ format. 

Thank you in advance!

Best,
HollowHeartNet

**Comment by akaszynski** [comment]
Hello,

Please see https://docs.pyvista.org/ for loading *.obj meshes and for saving resulting meshes.

**Comment by HollowHeartNet** [comment]
@akaszynski Thank you !
