### ISSUE TITLE
[Feature Request] Anaconda package

### ISSUE THREAD

**Issue by pietakio** [pyvista/pyacvd#16]
When time permits, <sup>...so, never</sup> it'd be great to publish a `conda` package for PyACVD. Assuming conda-forge, [hot behind-the-scenes automation](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch) will automatically bump the `conda` package for you on each PyPI bump – saving precious dev time for fun things like [full-blown ACVD bindings](https://github.com/pyvista/pyacvd/issues/10#issuecomment-652677017). :wink: 

Thanks for all the Pythonic volunteerism, Alex. PyACVD is jaw-droppingly awesome! The resulting meshes are a *big* improvement over standard implicit modelling techniques available in VTK and PyVista like marching cubes and flying edges.

**Comment by akaszynski** [comment]
Thanks!  There's a variety of things to do, but I do need practice creating conda packages for some of my other projects, so there's no reason why not to start here.  I'll add it on my todo, but it might be higher priority than you think.

**Comment by akaszynski** [comment]
Just added this a few hours ago:
https://anaconda.org/conda-forge/pyacvd

**Comment by pietakio** [comment]
Thank you so much!

**Comment by kalingibbons** [comment]
Can we push an updated Anaconda package with 0.28+? Now that the cell_data and point_data deprecation ran out, it seems like a good tiem.
