### ISSUE TITLE
pyvista 0.2.6 does not work with numpy 1.18.5

### ISSUE THREAD

**Issue by dslawinski-fp** [pyvista/pyacvd#18]
I'm trying to use pyvista in broader context (with tensorflow 2.3, which needs numpy 1.18.5). While I am aware 'its not your problem what is my current package setup'. I just want to know if you plan to support older versions of numpy?

For pyacvd 0.2.6:
creating fresh python 3.7 environment, and installing from pip: pyacvd==0.2.6 and then numpy 1.18.5: results in exception during import of pyacvd in python terminal/script:

> import pyacvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user123/progs/anaconda3/envs/envone37pv1/lib/python3.7/site-packages/pyacvd/__init__.py", line 1, in <module>
    from pyacvd.clustering import Clustering
  File "/home/user123/progs/anaconda3/envs/envone37pv1/lib/python3.7/site-packages/pyacvd/clustering.py", line 7, in <module>
    from pyacvd import _clustering
  File "pyacvd/cython/_clustering.pyx", line 1, in init pyacvd._clustering
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

For pyacvd 0.2.5:
creating fresh python 3.7 environment, and installing from pip: pyacvd==0.2.5 and then numpy 1.18.5: results in proper import of pyacvd in python terminal/script (all works ok)

**Comment by akaszynski** [comment]
Issue is we're building on a newer version of numpy.  I can change the version we build on so we support older numpy.

If possible, you can also rebuild `pyacvd` with your current install of numpy with:
```
pip install pyacvd --no-binary
```

**Comment by dslawinski-fp** [comment]
Using --no-binary reverts me back to 0.2.5.

Full scope of my attempts:

- `pip install pyacvd --no-binary`
  --no-binary option requires 1 argument

- Install of `numpy==1.18.5` and `pip install pyacvd --no-binary "pyacvd"`
  Reverts me back to `pyacvd` in version `0.2.5`
- Install of `numpy==1.18.5` and `pip install pyacvd==0.2.6 --no-binary "pyacvd"` (kinda defeats my purpose as I dont want to freeze pyacvd to use future changes/bugfixes, but still kinda strange as 0.2.6 is listed, but cannot be found)
  ERROR: Could not find a version that satisfies the requirement pyacvd==0.2.6 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.5, 0.2.6)
ERROR: No matching distribution found for pyacvd==0.2.6

I know that possible fix is to reinstall numpy after regular `pip install pyacvd` but Im not sure how it will affect stability of other packages that need 'old numpy', but if I were to use newer numpy, I wouldnt create such issue here

**Comment by akaszynski** [comment]
Try one of the following at https://stackoverflow.com/questions/33669846/

I'm rebuilding using <=1.20.  Give me a bit for that package to be out.

**Comment by akaszynski** [comment]
Just released `pyacvd==0.2.7` and tested it on Linux against `numpy==1.18.5` with no issue.  Please try installing latest with `pip` and let me know if this is still an issue.

**Comment by dslawinski-fp** [comment]
Just tested, works as intended. Thank you.
