### ISSUE TITLE
Python package not usable since build system update

### ISSUE THREAD

**Issue by lassoan** [pyvista/pyacvd#56]
Thank you for all your work with this package. Uniform resampling has been a very useful in 3D Slicer and worked very well until the recent revamping of the build system. Now we cannot use it at all, because the package depends on a specific VTK binary package version. We cannot use the VTK in PyPI, because we - as many others - cannot use the exact same VTK build options that are used for the PyPI package.

Now that the implementation is in C++ the clean solution would be to implement clustering as a VTK filter and use VTK's Python wrapping.

You may contact @jcfr (Jean-Christophe Fillion-Robin at Kitware) if you need help with building clean VTK remote modules that use VTK's built-in Python wrapper (see for example https://github.com/Slicer/vtkAddon).

**Comment by akaszynski** [comment]
@lassoan, I'm curious why this is the case since the new build using `nanobind` and `scikit-build-core` doesn't rely on a specific VTK version. Could you please post the error you're getting? [CMakeLists.txt](https://github.com/pyvista/pyacvd/blob/main/CMakeLists.txt) and [clustering.cpp](https://github.com/pyvista/pyacvd/blob/main/src/clustering.cpp) only rely on numpy.

**Comment by lassoan** [comment]
Thanks a lot for the quick response. Maybe I made a conclusion too quickly. I've started from this user report:

```text
[Python] Failed to compute output model: DLL load failed while importing _clustering: The specified module could not be found.
Traceback (most recent call last):
File “C:/Users/kucerabi/Desktop/Slicer 5.6.2/bin/…/lib/Slicer-5.6/qt-scripted-modules/SurfaceToolbox.py”, line 278, in onApplyButton
self.logic.applyFilters(self.parameterNode)
File “C:/Users/kucerabi/Desktop/Slicer 5.6.2/bin/…/lib/Slicer-5.6/qt-scripted-modules/SurfaceToolbox.py”, line 579, in applyFilters
SurfaceToolboxLogic.remesh(outputModel, outputModel,
File “C:/Users/kucerabi/Desktop/Slicer 5.6.2/bin/…/lib/Slicer-5.6/qt-scripted-modules/SurfaceToolbox.py”, line 404, in remesh
if not SurfaceToolboxLogic.installRemeshPrerequisites():
File “C:/Users/kucerabi/Desktop/Slicer 5.6.2/bin/…/lib/Slicer-5.6/qt-scripted-modules/SurfaceToolbox.py”, line 387, in installRemeshPrerequisites
import pyacvd
File "C:\Users\kucerabi\Desktop\Slicer 5.6.2\lib\Python\Lib\site-packages\pyacvd_init.py", line 3, in
from pyacvd.clustering import Clustering
File “C:\Users\kucerabi\Desktop\Slicer 5.6.2\lib\Python\Lib\site-packages\pyacvd\clustering.py”, line 16, in
from pyacvd import _clustering
ImportError: DLL load failed while importing _clustering: The specified module could not be found.
```

Then saw the relatively recent pyacvd build system changes and connected the two, but maybe that was just a coincidence. While pyacvd depends on pyvista, pyvista does not install VTK, so the version that Slicer has should work well.

I've tried the latest pyacvd on a fresh Slicer installation and it still worked well. So, now I suspect that the issue is not with pyacvd but the user may have some problem specific to that computer. It might be a too aggressive antivirus software that removes the .pyd file for some reason.

I'll update you here when I get feedback from the user.

**Comment by akaszynski** [comment]
Thanks for the update.

I would prefer not reverting since there's both build and performance benefits from the new approach.

**Comment by lassoan** [comment]
The user confirmed that downgrading to `pyacvd<0.3` solved the problem (https://discourse.slicer.org/t/importerror-with-uniform-remesh/38448/6). It seems the problem only occurs only on certain computers.

I've checked the dependencies of `_clustering.cp39-win_amd64.pyd` and I've found that they depend on very similar MSVCRT libraries, but there is a huge difference: pacvd<3 does not depend on OpenMP, while pyacvd-3.0.3 depends on OpenMP (LIBOMP140.X86_64.DLL). OpenMP is not part of the operating system. It may be installed by various developer tools and may be distributed as part of applications. I don't know what is the current guidance for using OpenMP in Python packages - not to use OpenMP, bundle an OpenMP DLL with the package, depend on some Python package that provides OpenMP, etc.

**Comment by akaszynski** [comment]
No problem, I can remove openmp as a dependency. It's only used for a minor operation and not for the main application. Thanks for looking into this.

**Comment by lassoan** [comment]
Sounds good! Let me know here when there is a new release to test with.

**Comment by akaszynski** [comment]
@lassoan, there's a new release at [pyacvd==0.3.1](https://pypi.org/project/pyacvd/0.3.1/) for you to test.

**Comment by lassoan** [comment]
Thanks a lot, I'll let you know if it fixes the issue on that user's computer.

**Comment by lassoan** [comment]
We haven't heard back from that user, so I assume everything is good. Thanks for taking care of this!
