### ISSUE TITLE
CeCILL-B License

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyacvd#6]
I think this software might need to be licensed under the "CeCILL-B FREE SOFTWARE LICENSE AGREEMENT" from https://github.com/valette/ACVD/blob/master/LICENSE.txt since this contains some of the original ACVD source.

I'm not positive about this though.

**Comment by akaszynski** [comment]
None of the original source code is included here.  The algorithm is similar, but I’ve made quite a few modifications on the original code and it’s in Cython rather in C++.  I’m not a lawyer, and I’m not 100% sure how you license code inspired by the original algorithm.  I’ll contact the original author.

**Comment by banesullivan** [comment]
Ah, if this project doesn't contain any code from the original project but rather implements concepts portrayed in their the original work, then **I think** it is fine to tag on an MIT License. However this could constitute a "derivative work" in some people's eyes and thus require adopting their license... 

I'd say stick with the MIT License and see if the original authors have any thoughts on this.
